### ISSUE TITLE
[US 07.01.01] Borrower want to return a book

### ISSUE THREAD

**Issue by essilfie** [CMPUT301F20T19/lendz#20]
#### User story
As a borrower, I want to hand over a book I borrowed by scanning the book ISBN code to denote the book as available.

#### Rationale
So that an Owner can know a book is available for return and for other Borrowers to know book is available

#### Story points
2

#### Risk level
Low

**Comment by kylemclean** [comment]
See this discussion thread for further details: https://eclass.srv.ualberta.ca/mod/forum/discuss.php?d=1516510
