### ISSUE TITLE
[US 07.02.01] Owner wants to receive a book

### ISSUE THREAD

**Issue by essilfie** [CMPUT301F20T19/lendz#21]
#### User story
As an owner, I want to receive a returned book by scanning the book ISBN code to confirm I have it available.

#### Rationale
So that other Borrowers will that the book is available to be borrowed again

#### Story points
2

#### Risk level
Low

**Comment by kylemclean** [comment]
See this discussion thread for further details: https://eclass.srv.ualberta.ca/mod/forum/discuss.php?d=1516510
