### ISSUE TITLE
[US 06.01.01] Owner wants to hand over a book

### ISSUE THREAD

**Issue by essilfie** [CMPUT301F20T19/lendz#22]
#### User story
As an owner, I want to hand over a book by scanning the book ISBN code and denoting the book as borrowed.

#### Rationale
So that other Borrowers will not book is not available

#### Story points
2

#### Risk level
low

**Comment by kylemclean** [comment]
See this discussion thread for further details: https://eclass.srv.ualberta.ca/mod/forum/discuss.php?d=1516510
