### ISSUE TITLE
[US 06.02.01] Borrower want to receive a book

### ISSUE THREAD

**Issue by essilfie** [CMPUT301F20T19/lendz#23]
#### User story
As a borrower, I want to receive an accepted book by scanning the book ISBN code to confirm I have borrowed it.

#### Rationale
So that the Owner know a book has been accepted.

#### Story points
2

#### Risk level
Low

**Comment by sohanislam001** [comment]
Suggested rationale: So that other borrowers can know that the book has been borrowed and hence is not available.

**Comment by kylemclean** [comment]
See this discussion thread for further details: https://eclass.srv.ualberta.ca/mod/forum/discuss.php?d=1516510
