### ISSUE TITLE
[US 09.01.01] Owner wants to set a Location 

### ISSUE THREAD

**Issue by essilfie** [CMPUT301F20T19/lendz#3]
#### User Story
As an Owner, I want to specify a geo location on a map of where to receive a book when I accept a request on the book

#### Rationale
 So that a Borrower can know where to receive the book

#### Story points
2

#### Risk level
Medium

**Comment by sohanislam001** [comment]
Suggested rationale: So that the owner can let the borrower know where the book to be borrowed can be picked up from.
