### ISSUE TITLE
[US 05.04.01] Borrower want to see a list of books they have requested that are accepted

### ISSUE THREAD

**Issue by essilfie** [CMPUT301F20T19/lendz#30]
#### User story
As a borrower, I want to view a list of books I have requested that are accepted, each book with its description, and owner username.

#### Rationale
So that I know which books I can go pick up and which ones to pick up first.

#### Story points
2

#### Risk level
Medium

**Comment by sohanislam001** [comment]
Suggested rationale: So that the borrower can know which books can picked up and from which users.
