### ISSUE TITLE
[US 09.02.01] Borrower wants Location

### ISSUE THREAD

**Issue by essilfie** [CMPUT301F20T19/lendz#6]
#### User story
As a Borrower, I want to view the geo location of where to receive a book I will be borrowing.

#### Rationale
So that the Owner can knows that Borrower intends on meeting at them at this location.

#### Story points
2

#### Risk level
Medium

**Comment by sohanislam001** [comment]
Suggested rationale: So that the borrower can know where the book to be borrowed can be picked up from.
